services:
  app:
    image: ghcr.io/${{ github.repository }}:latest
    ports:
      - "8000:80"
    volumes:
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
    env_file:
      - .env

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file:
      - .env
